### PR TITLE
Add falltergeist engine

### PR DESCRIPTION
**Pull request by Itxaka**
First time doing an engine, this project is pretty cool :D

Package is at https://gitlab.com/itxaka/falltergeist

Cheers!

### CODE REVIEW

**Comment by d10sfan** [comment]
Out of curiosity, how far is the project in terms of playing the game? Not too familiar with falltergeist

Nice to see some more contributors :)

**Comment by Itxaka** [comment]
> Out of curiosity, how far is the project in terms of playing the game? Not too familiar with falltergeist

Using latest version from develop branch, seems like the game is playable with some graphical issues (white squares) but nowhere it mentions if the game is even fully playable.

To be honest, the only reason I did falltergeist was because  I wanted to contribute and I had it on my library :D

I'll probably try another engine shortly

**Comment by dreamer** [comment]
@Itxaka thank you! I am sort-of preoccupied with my other projects but will come back to luxtorpeda over the weekend to review your package and hook it up with the rest :)

Do you want to be added as a package owner for falltergeist?

**Comment by Itxaka** [comment]
Sure, why not :)

**Comment by Itxaka** [comment]
ping @dreamer any news on this?

**Comment by Itxaka** [comment]
no movement here so closing this, feel free to reopen if needed in the future, it was a great exercise :D

**Pull request closed without merging**
